# Housing Prices Prediction System

### Loading Modules

In [6]:
# Standard modules
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


# sklearn modules 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from category_encoders import TargetEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [7]:
# loading the dataset
melbourne_data = pd.read_csv(r"C:\Users\DT\Desktop\Practice\Data\melb_data\melb_data.csv") # converting the dataset into a pandas dataframe
melbourne_data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

### Retrieving information about the Dataframe

In [8]:
print(melbourne_data.info()) # print information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB
None

### Splitting data into features and target

In [9]:
# splitting the dataset into features and target
X = melbourne_data.drop(['Price'], axis=1) # selects all features except the target variable 'Price'
y = melbourne_data.Price # selects the target variable 'Price'

### Splitting data into training and testing sets

In [10]:
# splitting the dataset into training and testing sets with 80% training and 20% testing with a random state of 42 for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Data Exploration

In [11]:
y_train.isna().sum() # check for missing values in the target variable of the training set

0

In [12]:
# exploring the X training data
X_train.head()

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
12796,Mount Waverley,37 Pascall St,4,h,S,Jellis,16/09/2017,14.2,3149.0,4.0,2.0,2.0,695.0,160.0,1970.0,NaN,-37.86127,145.14271,Eastern Metropolitan,13366.0
9642,Mount Waverley,23 Baily St,3,h,S,Ray,17/06/2017,14.2,3149.0,3.0,1.0,2.0,810.0,NaN,NaN,Monash,-37.86838,145.14664,Eastern Metropolitan,13366.0
3207,Hawthorn,5/70 Power St,2,u,S,Jellis,25/02/2017,4.6,3122.0,2.0,1.0,1.0,82.0,NaN,NaN,Boroondara,-37.81800,145.02680,Southern Metropolitan,11308.0
1698,Carlton North,24/635 Drummond St,2,u,S,hockingstuart,27/06/2016,3.2,3054.0,2.0,1.0,1.0,0.0,76.0,1975.0,Yarra,-37.79020,144.97000,Northern Metropolitan,3106.0
761,Bentleigh,3 Somers St,4,h,S,Woodards,22/05/2016,13.0,3204.0,4.0,2.0,1.0,292.0,NaN,NaN,Glen Eira,-37.91480,145.02430,Southern Metropolitan,6795.0

In [13]:
X_train.describe().style.format("{:,.2f}") # provides a statistical summary of the numeric features in the training dataset, including count, mean, standard deviation, minimum, maximum, and quartiles for each feature.

In [14]:
X_train.info() # this returns information about the training dataset, including the number of non-null entries, data types of each feature, and memory usage.

<class 'pandas.core.frame.DataFrame'>
Index: 10864 entries, 12796 to 7270
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         10864 non-null  object
 1   Address        10864 non-null  object
 2   Rooms          10864 non-null  int64
 3   Type           10864 non-null  object
 4   Method         10864 non-null  object
 5   SellerG        10864 non-null  object
 6   Date           10864 non-null  object
 7   Distance       10864 non-null  float64
 8   Postcode       10864 non-null  float64
 9   Bedroom2       10864 non-null  float64
 10  Bathroom       10864 non-null  float64
 11  Car            10814 non-null  float64
 12  Landsize       10864 non-null  float64
 13  BuildingArea   5735 non-null   float64
 14  YearBuilt      6578 non-null   float64
 15  CouncilArea    9774 non-null   object
 16  Lattitude      10864 non-null  float64
 17  Longtitude     10864 non-null  float64
 18  Regionname     10864 non-null  object
 19  Propertycount  10864 non-null  float64
dtypes: float64(11), int64(1), object(8)
memory usage: 1.7+ MB

### Missing Values

In [15]:
# checking for missing numbers
missing_values = X_train.isna().sum() # calculates the number of missing values in each feature of the training dataset and stores it in a variable called 'missing_values'.
missing_values[missing_values > 0] # displays the features with missing values and their corresponding counts

Car               50
BuildingArea    5129
YearBuilt       4286
CouncilArea     1090
dtype: int64

### Categorical Variables

In [16]:
categorical_features = X_train.select_dtypes(include=['object', 'string']).columns.tolist() # selects the categorical features from the training dataset and stores them in a variable called 'categorical_features'.
X_train[categorical_features].nunique()  # count unique values for each categorical feature

Suburb           306
Address        10726
Type               3
Method             5
SellerG          249
Date              58
CouncilArea       33
Regionname         8
dtype: int64

### Handling Missing Values and Categorical Variables
Since the unique values per each of the columns varies greatly, we will use difference encoding methods on the data

selecting the categorical features with more than 10 unique values for target encoding and the categorical features with 10 or fewer unique values for one-hot encoding, as well as the features to be dropped from the training dataset and the numeric features from the training dataset.

In [17]:
drop_col = ['Address', 'Postcode', 'Date']
# categorical_features = X_train.select_dtypes(include=['object']).columns # selects the categorical features from the training dataset and stores them in a variable called 'categorical_features'.

categorical_features = [
    col for col in categorical_features
    if col not in drop_col
] # filters out the features in 'drop_col' from the list of categorical features and stores the remaining categorical features in a variable called 'categorical_features'.

target_encode_col = [
    col for col in categorical_features
    if X_train[col].nunique() > 10
] # filters the categorical features to include only those with more than 10 unique values and stores them in a variable called 'target_encode_col'.

onehot_encode_col = [
    col for col in categorical_features
    if X_train[col].nunique() <= 10
] # filters the categorical features to include only those with 10 or fewer unique values and stores them in a variable called 'onehot_encode_col'.

numeric_features = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist() # selects the numeric features from the training dataset and stores them in a variable called 'numeric_features'.
numeric_features = [col for col in numeric_features if col not in drop_col] # filters out the features in 'drop_col' from the list of numeric features and stores the remaining numeric features in a variable called 'numeric_features'.

In [18]:
categorical_features

['Suburb', 'Type', 'Method', 'SellerG', 'CouncilArea', 'Regionname']

In [19]:
# Combines all selected features into a single list
total_features = target_encode_col + onehot_encode_col + numeric_features # combines the target encoded, one-hot encoded, and numeric features into a single list called 'total_features'.

# Selects the features in 'total_features' from the training and testing datasets
X_train_updated = X_train[total_features].copy() # creates a copy of the training dataset with only the selected features and stores it in a variable called 'X_train_updated'.
X_test_updated = X_test[total_features].copy() # creates a copy of the testing dataset with only the selected features and stores it in a variable called 'X_test_updated'.

In [20]:
print(X_train_updated.info()) # print information about the updated training dataset

<class 'pandas.core.frame.DataFrame'>
Index: 10864 entries, 12796 to 7270
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         10864 non-null  object
 1   SellerG        10864 non-null  object
 2   CouncilArea    9774 non-null   object
 3   Type           10864 non-null  object
 4   Method         10864 non-null  object
 5   Regionname     10864 non-null  object
 6   Rooms          10864 non-null  int64
 7   Distance       10864 non-null  float64
 8   Bedroom2       10864 non-null  float64
 9   Bathroom       10864 non-null  float64
 10  Car            10814 non-null  float64
 11  Landsize       10864 non-null  float64
 12  BuildingArea   5735 non-null   float64
 13  YearBuilt      6578 non-null   float64
 14  Lattitude      10864 non-null  float64
 15  Longtitude     10864 non-null  float64
 16  Propertycount  10864 non-null  float64
dtypes: float64(10), int64(1), object(6)
memory usage: 1.5+ MB
None

In [21]:
# numerical transformer pipeline for preprocessing numeric features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')), # replaces missing values in numeric features with the median value of the respective feature
    ('scaler', StandardScaler()) # standardizes the numeric features by removing the mean and scaling to unit variance
])

In [22]:
# categorical transformer pipeline for preprocessing categorical features
onehot_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')), # replaces missing values in categorical features with the most frequent value of the respective feature
    ('onehot', OneHotEncoder(handle_unknown='ignore')), # applies one-hot encoding to the categorical features, ignoring any unknown categories during transformation
])

In [23]:
target_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')), # replaces missing values in categorical features with the most frequent value of the respective feature  
    ('target', TargetEncoder()) # applies target encoding to the categorical features, encoding them based on the mean of the target variable for each category
])

In [24]:
# preprocessing both numerical and categorical features using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numeric_features), # applies the numerical transformer to the numeric features
        ('onehot', onehot_transformer, onehot_encode_col),
        ('target', target_transformer, target_encode_col)
    ]
)

In [25]:
model = LinearRegression() # creates an instance of the LinearRegression model and stores it in a variable called 'model'.

In [26]:
pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor), 
        ('model', model)
    ]) # creates a pipeline that first preprocesses the data using the 'preprocessor' and then fits the 'model' to the preprocessed data.

In [27]:
pipeline = pipeline.fit(X_train_updated, y_train)

In [28]:
y_pred = pipeline.predict(X_test_updated) # uses the fitted pipeline to make predictions on the updated testing dataset and stores the predicted values in a variable called 'y_pred'
mae = mean_absolute_error(y_test, y_pred) # calculates the mean absolute error between the actual and predicted values of the target variable in the testing dataset and stores it in a variable called 'mae'.
print("The mean square error is:", mae)

The mean square error is: 240134.05722810057

In [29]:
# the mean square error
# it is a measure of how close the predicted values are to the actual values. 
# It is calculated by taking the average of the squared differences between the predicted and actual values. 
# A lower mean square error indicates better model performance.
mse  = mean_squared_error(y_test, y_pred)
print("The mean square error: ", mse)

The mean square error:  128999114728.29285

In [30]:
# the root mean square error
# it is the square root of the mean square error.
rmse = np.sqrt(mse)
print("The root mean square error: ", rmse)

The root mean square error:  359164.4675191198

In [31]:
# the coefficient of determination
r_square = r2_score(y_test, y_pred)
print("The r squared value: ", r_square)

The r squared value:  0.6752401422734676

In [32]:
n = X_test.shape[0]
p = X_test.shape[1]

adj_r2 = 1 - (1 - r_square)* (n -1) / (n - p - 1)
print("Adjusted R square value is:", adj_r2)

Adjusted R square value is: 0.6728300505649218

Adjusted  
R2 asks a very simple question: "Did this new feature actually help the model predict better, or is it just taking up space?" If we add a strong, useful feature (like horsepower), the predictive power increases enough to beat the penalty, and our Adjusted R2 goes up

a parsimonious model is one that achieves strong predictive power using the simplest possible structure. The Akaike Information Criterion (AIC) and Bayesian Information Criterion (BIC) are statistical metrics designed to evaluate this exact balance.

When we build several different models to predict the exact same thing, we need a way to declare a mathematical winner. Both AIC (Akaike Information Criterion) and BIC (Bayesian Information Criterion) act as referees based on two strict rules:

Reward accuracy: The closer the predictions are to reality, the better the score.

Penalize bloat: Every time we add a new feature (variable) to the model, they add a penalty

In [33]:
import statsmodels.formula.api as smf
 
train_df = X_train_updated.copy()
train_df['Price'] = y_train
formula = 'Price ~ ' + ' + '.join(X_train_updated.columns) # this is the formula that we will use to predict the price of the house based on the features selected above
# which is the same as Price ~ Rooms + Distance + Postcode + Bedroom2 + Bathroom + Car + Landsize + BuildingArea + YearBuilt
model = smf.ols(formula=formula, data=train_df).fit() # this is the model that we will use to predict the price of the house based on the features selected above

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.747
Model:                            OLS   Adj. R-squared:                  0.719
Method:                 Least Squares   F-statistic:                     26.98
Date:                Wed, 01 Jul 2026   Prob (F-statistic):               0.00
Time:                        12:33:06   Log-Likelihood:                -70198.
No. Observations:                4959   AIC:                         1.414e+05
Df Residuals:                    4469   BIC:                         1.446e+05
Df Model:                         489
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                -1.437e+07   9.27e+07     -0.155      0.877   -1.96e+08    1.67e+08
Suburb[T.Aberfeldie]                      3.486e+05   1.32e+05      2.639      0.008    8.96e+04    6.08e+05
Suburb[T.Airport West]                    7.816e+04   2.75e+05      0.284      0.776   -4.61e+05    6.17e+05
Suburb[T.Albanvale]                          0.0010      0.006      0.156      0.876      -0.011       0.013
Suburb[T.Albert Park]                     3.832e+04    2.8e+05      0.137      0.891   -5.11e+05    5.87e+05
Suburb[T.Albion]                          1.757e+05   2.83e+05      0.622      0.534   -3.78e+05     7.3e+05
Suburb[T.Alphington]                      1.654e+05   2.93e+05      0.564      0.573    -4.1e+05    7.41e+05
Suburb[T.Altona]                          3.684e+04   2.96e+05      0.124      0.901   -5.44e+05    6.18e+05
Suburb[T.Altona Meadows]                 -1.781e+05   5.08e+05     -0.351      0.726   -1.17e+06    8.17e+05
Suburb[T.Altona North]                   -1.942e+05   2.78e+05     -0.700      0.484   -7.38e+05     3.5e+05
Suburb[T.Ardeer]                         -3.756e+04   4.79e+05     -0.078      0.938   -9.77e+05    9.02e+05
Suburb[T.Armadale]                       -6006.2248   1.76e+05     -0.034      0.973   -3.51e+05    3.39e+05
Suburb[T.Ascot Vale]                     -5.398e+04   5.38e+05     -0.100      0.920   -1.11e+06       1e+06
Suburb[T.Ashburton]                      -1.902e+05   3.38e+05     -0.562      0.574   -8.54e+05    4.73e+05
Suburb[T.Ashwood]                        -2.489e+05   3.73e+05     -0.667      0.505   -9.81e+05    4.83e+05
Suburb[T.Aspendale]                      -2.171e+04   3.39e+05     -0.064      0.949   -6.87e+05    6.44e+05
Suburb[T.Aspendale Gardens]              -4.933e-05      0.000     -0.155      0.877      -0.001       0.001
Suburb[T.Attwood]                         6.129e-07   3.96e-06      0.155      0.877   -7.16e-06    8.38e-06
Suburb[T.Avondale Heights]               -2.714e+05   3.73e+05     -0.727      0.467      -1e+06     4.6e+05
Suburb[T.Bacchus Marsh]                   1.469e-06   9.49e-06      0.155      0.877   -1.71e-05    2.01e-05
Suburb[T.Balaclava]                      -4.049e+05   3.36e+05     -1.204      0.229   -1.06e+06    2.54e+05
Suburb[T.Balwyn]                          2.063e+05   1.47e+05      1.406      0.160   -8.13e+04    4.94e+05
Suburb[T.Balwyn North]                    1.383e+05   2.37e+05      0.582      0.560   -3.27e+05    6.04e+05
Suburb[T.Bayswater]                       1.002e+04    6.7e+05      0.015      0.988    -1.3e+06    1.32e+06
Suburb[T.Bayswater North]                 -1.57e+05   5.76e+05     -0.273      0.785   -1.29e+06    9.72e+05
Suburb[T.Beaconsfield]                   -1.516e+05   1.09e+06     -0.140      0.889   -2.28e+06    1.98e+06
Suburb[T.Beaumaris]                       4.844e+05   3.08e+05      1.574      0.116   -1.19e+05    1.09e+06
Suburb[T.Bellfield]                      -7.201e+05   3.32e+06     -0.217      0.828   -7.23e+06    5.79e+06
Suburb[T.Bentleigh]                       1.569e+05   2.12e+05      0.739      0.460   -2.59e+05    5.73e+05
Suburb[T.Bentleigh East]                  6.463e+04   5.21e+05      0.124      0.901   -9.56e+05    1.09e+06
Suburb[T.Berwick]                        -7.733e+04   6.81e+05     -0.114      0.910   -1.41e+06    1.26e+06
Suburb[T.Black Rock]                      1.887e+05   4.38e+05      0.431      0.666   -6.69e+05    1.05e+06
Suburb[T.Blackburn]                       -3.88e+05   1.74e+06     -0.223      0.824    -3.8e+06    3.02e+06
Suburb[T.Blackburn North]                -3.717e+05   2.03e+06     -0.183      0.855   -4.36e+06    3.61e+06
Suburb[T.Blackburn South]                -3.072e+05   1.87e+06     -0.164      0.870   -3.98e+06    3.37e+06
Suburb[T.Bonbeach]                       -1.279e+05   4.33e+05     -0.296      0.768   -9.76e+05     7.2e+05
Suburb[T.Boronia]                        -5.424e+04   2.69e+05     -0.201      0.840   -5.82e+05    4.74e+05
Suburb[T.Box Hill]                       -1.238e+05   1.83e+06     -0.068      0.946   -3.72e+06    3.47e+06
Suburb[T.Braybrook]                       -1.03e+05   1.79e+05     -0.574      0.566   -4.55e+05    2.49e+05
Suburb[T.Briar Hill]                     -1.653e+05    3.3e+06     -0.050      0.960   -6.63e+06     6.3e+06
Suburb[T.Brighton]                        6.277e+05   5.22e+05      1.203      0.229   -3.95e+05    1.65e+06
Suburb[T.Brighton East]                   1.984e+05   2.11e+05      0.942      0.346   -2.14e+05    6.11e+05
Suburb[T.Broadmeadows]                   -1.336e+04   2.02e+05     -0.066      0.947   -4.09e+05    3.82e+05
Suburb[T.Brooklyn]                        5.727e+04   4.25e+05      0.135      0.893   -7.76e+05     8.9e+05
Suburb[T.Brunswick]                      -1.061e+04   9.11e+05     -0.012      0.991    -1.8e+06    1.78e+06
Suburb[T.Brunswick East]                 -8.601e+04   4.51e+05     -0.191      0.849    -9.7e+05    7.98e+05
Suburb[T.Brunswick West]                 -1.717e+05   5.38e+05     -0.319      0.750   -1.23e+06    8.83e+05
Suburb[T.Bulleen]                        -1.952e+05   5.53e+05     -0.353      0.724   -1.28e+06    8.89e+05
Suburb[T.Bullengarook]                   -5.036e-07   3.23e-06     -0.156      0.876   -6.84e-06    5.84e-06
Suburb[T.Bundoora]                        3.912e+05   6.87e+05      0.569      0.569   -9.56e+05    1.74e+06
Suburb[T.Burnley]                         6.278e+04   4.25e+05      0.148      0.882   -7.69e+05    8.95e+05
Suburb[T.Burnside]                         4.61e-07   2.96e-06      0.156      0.876   -5.35e-06    6.27e-06
Suburb[T.Burnside Heights]                5.759e+04   4.78e+05      0.121      0.904   -8.79e+05    9.94e+05
Suburb[T.Burwood]                        -1.719e+05    1.5e+05     -1.147      0.251   -4.66e+05    1.22e+05
Suburb[T.Burwood East]                   -3.806e+05   1.92e+06     -0.199      0.843   -4.14e+06    3.38e+06
Suburb[T.Cairnlea]                        5.337e+04   3.27e+05      0.163      0.871   -5.88e+05    6.95e+05
Suburb[T.Camberwell]                     -3.367e+04   3.27e+05     -0.103      0.918   -6.76e+05    6.08e+05
Suburb[T.Campbellfield]                   1.721e-08   9.84e-08      0.175      0.861   -1.76e-07     2.1e-07
Suburb[T.Canterbury]                      4.915e+05   3.14e+05      1.564      0.118   -1.25e+05    1.11e+06
Suburb[T.Carlton]                         2.714e+05   1.46e+06      0.186      0.852   -2.58e+06    3.13e+06
Suburb[T.Carlton North]                   5.581e+05   1.54e+05      3.615      0.000    2.55e+05    8.61e+05
Suburb[T.Carnegie]                        1.951e+05    2.6e+05      0.750      0.453   -3.15e+05    7.05e+05
Suburb[T.Caroline Springs]                8.208e+04   3.24e+05      0.253      0.800   -5.53e+05    7.17e+05
Suburb[T.Carrum]                          5.695e+04   4.08e+05      0.139      0.889   -7.44e+05    8.57e+05
Suburb[T.Carrum Downs]                   -1.898e+05   1.79e+05     -1.062      0.288    -5.4e+05     1.6e+05
Suburb[T.Caulfield]                      -2.666e+05   4.55e+05     -0.586      0.558   -1.16e+06    6.26e+05
Suburb[T.Caulfield East]                  3.826e-08   2.63e-07      0.146      0.884   -4.77e-07    5.54e-07
Suburb[T.Caulfield North]                 1.916e+05   2.34e+05      0.820      0.412   -2.66e+05     6.5e+05
Suburb[T.Caulfield South]                  1.14e+05   2.21e+05      0.515      0.606    -3.2e+05    5.48e+05
Suburb[T.Chadstone]                      -2.569e+05   3.14e+05     -0.818      0.414   -8.73e+05    3.59e+05
Suburb[T.Chelsea]                         2.261e+05   3.01e+05      0.752      0.452   -3.63e+05    8.15e+05
Suburb[T.Chelsea Heights]                 -3.57e+05   4.79e+05     -0.745      0.456    -1.3e+06    5.82e+05
Suburb[T.Cheltenham]                      5.393e+04   4.22e+05      0.128      0.898   -7.74e+05    8.82e+05
Suburb[T.Chirnside Park]                  1.299e+05   6.02e+05      0.216      0.829   -1.05e+06    1.31e+06
Suburb[T.Clarinda]                       -4.517e+05   4.17e+05     -1.084      0.278   -1.27e+06    3.65e+05
Suburb[T.Clayton]                         1.159e+05   2.38e+05      0.487      0.626    -3.5e+05    5.82e+05
Suburb[T.Clayton South]                   1.235e-07   8.16e-07      0.151      0.880   -1.48e-06    1.72e-06
Suburb[T.Clifton Hill]                    1.491e+05    1.5e+05      0.993      0.321   -1.45e+05    4.44e+05
Suburb[T.Coburg]                         -9.233e+04   8.53e+05     -0.108      0.914   -1.76e+06    1.58e+06
Suburb[T.Coburg North]                   -2.242e+05   4.27e+05     -0.525      0.599   -1.06e+06    6.13e+05
Suburb[T.Collingwood]                     -5.92e+04   1.12e+05     -0.529      0.597   -2.79e+05     1.6e+05
Suburb[T.Coolaroo]                        4.461e-08   2.86e-07      0.156      0.876   -5.16e-07    6.05e-07
Suburb[T.Craigieburn]                      4.34e+05   1.25e+06      0.346      0.729   -2.02e+06    2.89e+06
Suburb[T.Cranbourne]                      3.085e-08   2.19e-07      0.141      0.888   -3.99e-07    4.61e-07
Suburb[T.Cranbourne North]               -2.551e+05   4.66e+05     -0.547      0.584   -1.17e+06    6.59e+05
Suburb[T.Cremorne]                       -6.553e+04   3.25e+05     -0.202      0.840   -7.02e+05    5.71e+05
Suburb[T.Croydon]                         9.434e+04   3.69e+05      0.256      0.798    -6.3e+05    8.18e+05
Suburb[T.Croydon Hills]                  -1.535e+05   7.68e+05     -0.200      0.842   -1.66e+06    1.35e+06
Suburb[T.Croydon North]                  -9.056e+04   6.13e+05     -0.148      0.883   -1.29e+06    1.11e+06
Suburb[T.Croydon South]                  -9.754e-10   2.71e-08     -0.036      0.971   -5.41e-08    5.21e-08
Suburb[T.Dallas]                          8.123e-08   5.18e-07      0.157      0.875   -9.34e-07     1.1e-06
Suburb[T.Dandenong]                       1.012e+05   2.88e+05      0.352      0.725   -4.63e+05    6.66e+05
Suburb[T.Dandenong North]                -1.581e+04   2.71e+05     -0.058      0.953   -5.47e+05    5.15e+05
Suburb[T.Deepdene]                        3.703e-08   2.42e-07      0.153      0.879   -4.38e-07    5.12e-07
Suburb[T.Deer Park]                       9.331e+04   3.88e+05      0.240      0.810   -6.68e+05    8.55e+05
Suburb[T.Delahey]                         5.518e+04   2.91e+05      0.189      0.850   -5.16e+05    6.26e+05
Suburb[T.Derrimut]                       -3.946e+05    4.3e+05     -0.918      0.359   -1.24e+06    4.48e+05
Suburb[T.Diamond Creek]                  -2.522e+05   7.77e+05     -0.325      0.745   -1.77e+06    1.27e+06
Suburb[T.Diggers Rest]                    5.138e-08   3.12e-07      0.165      0.869   -5.59e-07    6.62e-07
Suburb[T.Dingley Village]                -8.275e+04   1.82e+05     -0.453      0.650   -4.41e+05    2.75e+05
Suburb[T.Docklands]                      -2.431e-08   1.37e-07     -0.177      0.859   -2.93e-07    2.44e-07
Suburb[T.Doncaster]                       4.037e+04    1.3e+05      0.309      0.757   -2.15e+05    2.96e+05
Suburb[T.Doncaster East]                  1.321e+05   1.32e+05      1.002      0.316   -1.26e+05    3.91e+05
Suburb[T.Donvale]                        -1.906e+05   6.02e+05     -0.317      0.752   -1.37e+06     9.9e+05
Suburb[T.Doreen]                         -7.068e+04    5.2e+05     -0.136      0.892   -1.09e+06    9.49e+05
Suburb[T.Doveton]                         6.312e+04   6.35e+05      0.099      0.921   -1.18e+06    1.31e+06
Suburb[T.Eaglemont]                      -1.124e+05   3.24e+06     -0.035      0.972   -6.47e+06    6.24e+06
Suburb[T.East Melbourne]                  7.048e+05   1.09e+06      0.649      0.516   -1.42e+06    2.83e+06
Suburb[T.Edithvale]                      -1.939e+05   3.64e+05     -0.533      0.594   -9.08e+05     5.2e+05
Suburb[T.Elsternwick]                      1.42e+05   2.18e+05      0.652      0.514   -2.85e+05    5.69e+05
Suburb[T.Eltham]                         -6.686e+05   2.78e+06     -0.241      0.810   -6.12e+06    4.78e+06
Suburb[T.Eltham North]                   -6.064e+05   3.24e+06     -0.187      0.852   -6.96e+06    5.75e+06
Suburb[T.Elwood]                          -1.72e+05   3.58e+05     -0.480      0.631   -8.74e+05     5.3e+05
Suburb[T.Endeavour Hills]                -1.028e+05    2.6e+05     -0.395      0.693   -6.12e+05    4.07e+05
Suburb[T.Epping]                          6.276e+05   8.16e+05      0.769      0.442   -9.73e+05    2.23e+06
Suburb[T.Essendon]                        1.986e+05   8.15e+05      0.244      0.808    -1.4e+06     1.8e+06
Suburb[T.Essendon North]                  9.399e+04    1.6e+05      0.588      0.557    -2.2e+05    4.08e+05
Suburb[T.Essendon West]                  -9.408e+04   1.52e+05     -0.617      0.537   -3.93e+05    2.05e+05
Suburb[T.Fairfield]                       1.174e+05   2.41e+05      0.486      0.627   -3.56e+05     5.9e+05
Suburb[T.Fawkner]                        -1.288e+05   4.61e+05     -0.279      0.780   -1.03e+06    7.75e+05
Suburb[T.Ferntree Gully]                 -1.476e+05   1.83e+05     -0.808      0.419   -5.06e+05    2.11e+05
Suburb[T.Fitzroy]                         1.637e+05    2.2e+05      0.745      0.456   -2.67e+05    5.94e+05
Suburb[T.Fitzroy North]                   1.783e+05   2.57e+05      0.693      0.488   -3.26e+05    6.82e+05
Suburb[T.Flemington]                       5.26e+04   1.19e+06      0.044      0.965   -2.27e+06    2.38e+06
Suburb[T.Footscray]                       6.973e+04   2.24e+05      0.311      0.756    -3.7e+05    5.09e+05
Suburb[T.Forest Hill]                    -3.764e+05   1.89e+06     -0.199      0.842   -4.09e+06    3.33e+06
Suburb[T.Frankston]                      -2.047e+04    8.7e+05     -0.024      0.981   -1.73e+06    1.68e+06
Suburb[T.Frankston North]                -2.123e+05   7.25e+05     -0.293      0.770   -1.63e+06    1.21e+06
Suburb[T.Frankston South]                -1.596e+04   2.83e+05     -0.056      0.955   -5.71e+05    5.39e+05
Suburb[T.Gardenvale]                     -1.016e+05   6.24e+05     -0.163      0.871   -1.33e+06    1.12e+06
Suburb[T.Gisborne]                         2.06e+05   2.28e+05      0.903      0.366   -2.41e+05    6.53e+05
Suburb[T.Gladstone Park]                 -4.292e+05   9.57e+05     -0.449      0.654    -2.3e+06    1.45e+06
Suburb[T.Glen Huntly]                     7.212e+04   4.35e+05      0.166      0.868   -7.81e+05    9.25e+05
Suburb[T.Glen Iris]                       4.799e+04   4.61e+05      0.104      0.917   -8.57e+05    9.52e+05
Suburb[T.Glen Waverley]                  -7.608e+04   8.08e+05     -0.094      0.925   -1.66e+06    1.51e+06
Suburb[T.Glenroy]                        -4.544e+04   6.92e+05     -0.066      0.948    -1.4e+06    1.31e+06
Suburb[T.Gowanbrae]                      -4.925e+05   1.23e+06     -0.401      0.688    -2.9e+06    1.91e+06
Suburb[T.Greensborough]                   5.165e+05   5.53e+05      0.935      0.350   -5.67e+05     1.6e+06
Suburb[T.Greenvale]                      -1.227e+05   2.74e+05     -0.448      0.654   -6.59e+05    4.14e+05
Suburb[T.Hadfield]                       -1.372e+05   4.63e+05     -0.296      0.767   -1.05e+06    7.71e+05
Suburb[T.Hallam]                         -9.454e+04   3.71e+05     -0.255      0.799   -8.21e+05    6.32e+05
Suburb[T.Hampton]                         2.889e+05   2.05e+05      1.411      0.158   -1.12e+05     6.9e+05
Suburb[T.Hampton East]                    8.942e+04    4.4e+05      0.203      0.839   -7.74e+05    9.53e+05
Suburb[T.Hampton Park]                    1.935e+05   3.58e+05      0.540      0.589   -5.08e+05    8.95e+05
Suburb[T.Hawthorn]                       -5.624e+04   5.89e+05     -0.095      0.924   -1.21e+06     1.1e+06
Suburb[T.Hawthorn East]                  -1.063e+05   1.54e+05     -0.689      0.491   -4.09e+05    1.96e+05
Suburb[T.Healesville]                     4.299e+05   3.41e+05      1.262      0.207   -2.38e+05     1.1e+06
Suburb[T.Heathmont]                       3.127e+04   5.09e+05      0.061      0.951   -9.67e+05    1.03e+06
Suburb[T.Heidelberg]                      -4.04e+05   3.12e+06     -0.130      0.897   -6.52e+06    5.71e+06
Suburb[T.Heidelberg Heights]             -6.378e+05    3.1e+06     -0.206      0.837   -6.72e+06    5.44e+06
Suburb[T.Heidelberg West]                -6.661e+05   3.12e+06     -0.213      0.831   -6.78e+06    5.45e+06
Suburb[T.Highett]                         8.972e+04   2.61e+05      0.343      0.731   -4.23e+05    6.02e+05
Suburb[T.Hillside]                        2.416e+05   1.86e+05      1.301      0.193   -1.22e+05    6.06e+05
Suburb[T.Hoppers Crossing]                3.251e+04   2.51e+05      0.130      0.897   -4.59e+05    5.24e+05
Suburb[T.Hughesdale]                     -1.962e+05   3.45e+05     -0.569      0.569   -8.72e+05     4.8e+05
Suburb[T.Huntingdale]                    -4.333e+05   6.78e+05     -0.639      0.523   -1.76e+06    8.96e+05
Suburb[T.Hurstbridge]                    -5.087e+05   1.09e+06     -0.466      0.641   -2.65e+06    1.63e+06
Suburb[T.Ivanhoe]                        -2.724e+05   2.84e+06     -0.096      0.923   -5.83e+06    5.29e+06
Suburb[T.Ivanhoe East]                    5.529e+04   3.25e+06      0.017      0.986   -6.32e+06    6.44e+06
Suburb[T.Jacana]                         -5.701e+04   3.14e+05     -0.181      0.856   -6.74e+05     5.6e+05
Suburb[T.Kealba]                          -1.22e+05   3.78e+05     -0.322      0.747   -8.64e+05     6.2e+05
Suburb[T.Keilor]                          1.845e+05    3.6e+05      0.513      0.608   -5.21e+05     8.9e+05
Suburb[T.Keilor Downs]                    5.383e+04   2.45e+05      0.219      0.826   -4.27e+05    5.35e+05
Suburb[T.Keilor East]                    -1.008e+05    4.8e+05     -0.210      0.834   -1.04e+06     8.4e+05
Suburb[T.Keilor Lodge]                   -1.511e-08   9.75e-08     -0.155      0.877   -2.06e-07    1.76e-07
Suburb[T.Keilor Park]                     1.911e+05   3.86e+05      0.495      0.620   -5.65e+05    9.47e+05
Suburb[T.Kensington]                       1.91e+05   1.33e+06      0.144      0.886   -2.41e+06     2.8e+06
Suburb[T.Kew]                            -1.045e+05   4.92e+05     -0.212      0.832   -1.07e+06     8.6e+05
Suburb[T.Kew East]                       -1.205e+05   3.63e+05     -0.332      0.740   -8.32e+05    5.91e+05
Suburb[T.Keysborough]                    -9.697e+04   2.51e+05     -0.386      0.700    -5.9e+05    3.96e+05
Suburb[T.Kilsyth]                         4.901e-09   2.24e-08      0.219      0.827    -3.9e-08    4.88e-08
Suburb[T.Kings Park]                     -1.126e+05   2.83e+05     -0.398      0.691   -6.68e+05    4.43e+05
Suburb[T.Kingsbury]                      -5.911e+04   4.06e+05     -0.146      0.884   -8.55e+05    7.36e+05

In [34]:
print("AIC:", model.aic) # AIC (Akaike Information Criterion) is a measure of the relative quality of a statistical model for a given set of data.
#It is used to compare different models and select the best one. A lower AIC value indicates a better-fitting model.



print("BIC:", model.bic) # BIC (Bayesian Information Criterion) is another measure of the relative quality of a statistical model. 
#It penalizes more complex models more heavily than AIC. A lower BIC value indicates a better-fitting model.

AIC: 141375.76836491274
BIC: 144565.1584642924